GET http://localhost:3000/api
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoxLCJ1c2VybmFtZSI6IkRhcmlvUHJhemVyZXMiLCJlbWFpbCI6ImRhcmlvZWRnYXJAZ21haWwuY29tIn0sImlhdCI6MTY1Mzc2MzQzOH0.FuKF99BSXGSRp8VSyQx2OaohubbrtYHB4o70AUDq3q
###
GET  http://localhost:3000/api/posts/628bfd265bcd640deb72a4ee
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoxLCJ1c2VybmFtZSI6IkRhcmlvUHJhemVyZXMiLCJlbWFpbCI6ImRhcmlvZWRnYXJAZ21haWwuY29tIn0sImlhdCI6MTY1Mzc2MzQzOH0.FuKF99BSXGSRp8VSyQx2OaohubbrtYHB4o70AUDq3q4
###
GET http://localhost:3000/api/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoxLCJ1c2VybmFtZSI6IkRhcmlvUHJhemVyZXMiLCJlbWFpbCI6ImRhcmlvZWRnYXJAZ21haWwuY29tIn0sImlhdCI6MTY1Mzc2MzQzOH0.FuKF99BSXGSRp8VSyQx2OaohubbrtYHB4o70AUDq3q
###
POST  http://localhost:3000/api/login